FROM openjdk:8-jre-alpine
WORKDIR /opt/app

# install script dependencies
RUN apk add --update netcat-openbsd curl && rm -rf /var/cache/apk/*

ADD elastic-apm-agent-*.jar /opt/app/elastic-apm-agent.jar