FROM bitnami/minideb AS deb_extractor
RUN cd /tmp && \
    apt-get update && apt-get download \
        netcat-openbsd curl && \
    mkdir /dpkg && \
    for deb in *.deb; do dpkg --extract $deb /dpkg || exit 10; done

FROM gcr.io/distroless/java17-debian12
WORKDIR /opt/app

COPY --from=deb_extractor /dpkg /
COPY HttpHealthcheck.java /opt/app/HttpHealthcheck.java
COPY elastic-apm-agent-*.jar /opt/app/elastic-apm-agent.jar